### ISSUE TITLE
seg fault when no devices are present

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-sweeper-action#31]
> This workflow action needs to handle the error properly if there are no metal device instances to delete in the project. Currently it throws a segmentation fault error. But this error needs to be handled and the function should exit gracefully with a proper error message.

**Comment by chefgs** [comment]
Hello @displague 
- As discussed over email, please find the workflow [error log](https://github.com/chefgs/equinix_demos/actions/runs/7947524728/job/21696445307) for the workflow I've created.

- Also please find the link to [workflow](https://github.com/chefgs/equinix_demos/blob/main/.github/workflows/delete_workflow.yml) for your reference.

- [Readme](https://github.com/chefgs/equinix_demos/blob/main/workflow_docs/equinix_delete_workflow_doc.md) file for the workflow.

**Comment by ctreatma** [comment]
@chefgs it looks like that sweeper action was run with a project name rather than a project ID.  The workflow output shows that the project ID passed in was `gsproject`, but Equinix Metal project IDs are UUIDs that look something like `01234567-89ab-cdef-d3ad-0123456789ab`.  These docs show how to use the Metal Console to look up the ID for your project: https://deploy.equinix.com/developers/docs/metal/projects/managing-a-project/#project-settings

Could you re-run the workflow using the project ID and let us know if the error still occurs?

**Comment by chefgs** [comment]
@ctreatma Yes, thanks for clarifying. It is mistake from my end, that I used project name instead of project ID. 
After using project ID, I could not see the issue now. The workflow [ran successfully](https://github.com/chefgs/equinix_demos/actions/runs/7992709350/job/21826843147).

But still in the case of using the project name or any other value other than project ID, the error message can be meaningful instead of seg fault and function can exit gracefully.

Thanks in advance.

**Comment by chefgs** [comment]
Just to add more info, it is throwing seg fault in vlan [part of code](https://github.com/equinix-labs/metal-sweeper-action/blob/41b456f3c9291be647867eef728f14069d94e7e6/main.go#L67C1-L71C4).
```
WARNING: 2024/02/18 07:51:42 main.go:51: Could not list devices 404 Not Found Not found
WARNING: 2024/02/18 07:51:42 main.go:64: Could not list vlans 404 Not Found Not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6a4159]

goroutine 1 [running]:
main.main()
	/code/main.go:67 +0x8b9
```

**Comment by displague** [comment]
Closing this issue and opening a new issue around input validation - we can assert that project ids are uuids.
